config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'

  get    '/users/:id',           to: 'users#show'
  get    '/login',               to: 'users#login'
  post   '/signup',	             to: 'users#create'
  post   '/login',     	         to: 'sessions#create'
  delete '/logout',              to: 'sessions#destroy'
  get    '/submit',              to: 'posts#new'
  post   '/submit',              to: 'posts#create'
  get    '/posts',               to: 'posts#index'
  get    '/posts/:id',           to: 'posts#show'
  post   '/posts/:id/upvote',    to: 'posts#upvote'
  get    '/comments',            to: 'comments#index'
  get    '/comments/:id',        to: 'comments#show'
  post   '/comments/new',        to: 'comments#create'
  post   '/comments/:id/upvote', to: 'comments#upvote'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :url, presence: true

  has_many :comments
  has_many :votes, as: :votable

  def votes_count
    votes.length + points
  end

  def comment_count
    comments.length
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[upvote create]

  def new; end

  def create
    @post = current_user.posts.build(post_params)
    redirect_to root_url if @post.save
  end

  def show
    @post = Post.find_by(id: params[:id])
    comments = Comment.includes(:user, :votes).where(post_id: @post.id).order('created_at DESC')
    @comment_tree = comment_tree(comments)
  end

  def index
    conditions = {}

    if params[:date]
      begin
        @date = Date.parse(params[:date])
        conditions[:created_at] = @date.beginning_of_day..@date.end_of_day
      rescue ArgumentError
        @date = Date.today
      end
    end

    if params[:user_id]
      user_id = params[:user_id]
      @username = User.find_by(id: user_id)
      conditions[:user_id] = user_id
    end

    @page = params[:page] || 1
    @posts = Post.includes(:votes, :comments, :user)
                 .where(conditions)
                 .order('created_at DESC')
                 .paginate(page: @page, per_page: 30)
  end

  def past
    date = params[:date] || Date.today

    @date = begin
      Date.parse(date.to_s)
    rescue ArgumentError
      Date.today
    end

    @page = params[:page] || 1
    @posts = Post.includes(:votes, :comments, :user)
                 .where(created_at: (@date.beginning_of_day..@date.end_of_day))
                 .order('created_at DESC').paginate(page: @page, per_page: 30)

    render :index
  end

  def upvote
    votable = { type: 'Post', id: params[:id] }

    if current_user.upvoted?(votable)
      current_user.remove_vote(votable)
    else
      current_user.upvote(votable)
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.permit(:title, :url)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  # transform a tree of comments:
  # A
  #   B
  #     C
  #     D
  #   E
  #   F
  # into a list sorted from top to down:
  # [A, B, C, D, E, F]
  # where every comment is wraped as {comment: Comment, depth: Integer}
  def comment_tree(comments)
    candidates = [nil]
    flat_comments = []

    until candidates.empty?
      current_candidate = candidates.pop
      flat_comments.push(current_candidate) unless current_candidate.nil?

      selected = comments.select do |comment|
        comment.parent_id == (current_candidate.nil? ? nil : current_candidate.id)
      end

      selected.reverse.each do |c|
        candidates.push(c)
      end
    end

    parent = nil
    stack_of_previous = []
    depth = -1
    tree = []

    flat_comments.each do |c|
      until c.parent_id == stack_of_previous.last
        stack_of_previous.pop
        depth -= 1
      end

      stack_of_previous.push(c.id)
      depth += 1

      tree.push({ comment: c, depth: depth })
    end

    tree
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/index.html.erb
<tr id="pagespace" title="" style="height:10px"></tr>
<tr>
	<td>
		<table border="0" cellpadding="0" cellspacing="0" class="itemlist">
      <tbody>
        <% unless @date.nil? %>
          <tr>
            <td colspan="2"></td>
            <td>Stories from <%= @date %></td>
          </tr>
          <tr style="height:9px"></tr>
          <tr>
            <td colspan="2"></td>
            <td>
              Go back a
              <span class="hnmore"><%= link_to "day", "/posts?date=#{@date.prev_day}" %></span>.
              Go forward a
              <span class="hnmore"><%= link_to "day", "/posts?date=#{@date.next_day}" %></span>.
            </td>
          </tr>
          <tr style="height:14px"></tr>
        <% end %>
        <% @posts.each_with_index do |post, index| %>
          <tr class="athing">
      		  <td align="right" valign="top" class="title">
      			  <span class="rank">
                <%= (index + 1).to_s + '.' %>
              </span>
      		  </td>
            <td valign="top" class="votelinks">
              <center>
                <%= link_to content_tag(:div, '', class: "votearrow", title: "upvote"),
                            "posts/#{post.id}/upvote", method: :post %>
              </center>
            </td>
      		  <td class="title">
              <%= link_to post.title, post.url.to_s, class: "storylink" %>
      			  <span class="sitebit comhead">(<span class="sitestr"><%= host_of_url(post.url) %></span>)</span>
      		  </td>
      	  </tr>

          <tr>
            <td colspan="2"></td>
            <td class="subtext"> 
              <%= pluralize(post.votes_count, 'point') %>
              <%= link_to "by " + post.user.name, "/users/#{post.user.id}", class: "hnuser" %>
              <span class="age">
                <%= link_to time_ago_in_words(post.created_at) + " ago", "/posts/#{post.id}" %>
              </span>
            | <%= link_to pluralize(post.comment_count, 'comment'), "/posts/#{post.id}" %>
            </td>
          </tr>

          <tr class="morespace" style="height:10px"></tr>

        <% end %>

        <tr>
          <td colspan="2"></td>
          <td class="title">
            <%= link_to "More", "/posts?page=#{(@page.to_i + 1).to_s}", class: "morelink" %>
          </td>
        </tr>
			</tbody>
		</table>
  </td>
</tr>

app/views/posts/new.html.erb
<tr>
<td>
<%= form_with(model: @post, url: submit_path, local: true) do |f| %>
  <table border="0">
    <tbody>
      <tr>
        <td>title</td>
        <td>
          <%= f.text_field :title, type: "text", size: "50" %>
          <span style="margin-left:10px"></span>
        </td>
      </tr>
      <tr>
        <td>url</td>
        <td>
          <%= f.text_field :url, type: "url", size: "50" %>
        </td>
      </tr>
      <tr>
        <td>
        <%= f.submit "submit" %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>
</td>
</tr>

app/views/posts/show.html.erb
<tr id="pagespace" style="height:10px"></tr>
<td>
  <table class="fatitem" border="0">
    <tbody>
      <tr class="athing" id="">
        <td align="right" valign="top" class="title">
          <span class="rank"></span>
        </td>
        <td valign="top" class="votelinks">
          <center>
            <%= link_to content_tag(:div, '', class: "votearrow", title: "upvote"),
                        "/posts/#{@post.id}/upvote", method: :post %>
          </center>
        </td>
        <td class="title">
          <%= link_to @post.title, @post.url.to_s, class: "storylink" %>
          <span class="sitebit comhead">(<span class="sitestr"><%= host_of_url(@post.url) %></span>)</span>
        </td>
      </tr>
      
      <tr>
        <td colspan="2"></td>
        <td class="subtext">
          <%= pluralize(@post.votes_count, 'point') %>
          by
          <%= link_to @post.user.name, "/users/#{@post.user.id}", class: "hnuser" %>
          <span class="age">
            <%= link_to time_ago_in_words(@post.created_at) + " ago", "/posts/#{@post.id}" %>
          </span>
        </td>
      </tr>
      
      <tr style="height:10px"></tr>
      <tr>
        <td colspan="2"></td>
        <td>
          <%= form_with(model: @comment, url: '/comments/new', local: true) do |f| %>
            <%= hidden_field_tag "post", @post.id %>
            <%= f.text_area :content, rows: "6", cols: "60" %>
            <br><br>
            <%= f.submit "submit" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <br><br>

  
  <table border="0" class="comment-tree">
    <tbody>
      <% @comment_tree.each_with_index do |node, ind| %>
        <% comment = node[:comment] %>
        <% depth = node[:depth] %>
        <tr class="athing comtr">
          <td>
            <table border="0">
              <tbody>
                <tr>
                  <td class="ind">
                    <img src="/s.gif" height="1" width="<%= 40 * depth %>">
                  </td>
                  <td valign="top" class="votelinks">
                    <center>
                      <%= link_to content_tag(:div, '', class: "votearrow", title: "upvote"),
                                  "/comments/#{comment.id}/upvote", method: :post %>
                    </center>
                  </td>
              <td class="default">
                <div style="margin-top:2px; margin-bottom:-10px;">
                  <span class="comhead">
                    <%= pluralize(comment.votes_count, 'point') %> by
                    <%= link_to comment.user.name, "/user/#{comment.user.id}", class: "hnuser" %>
                    <span class="age">
                      <%= link_to time_ago_in_words(comment.created_at) + " ago", "/comments/#{comment.id}" %>
                    </span>
                  </span>
                </div>
                <br>
                <div class="comment">
                  <span class="commtext c00">
                    <%= comment.content %>
                      <div class="reply">
                        <p>
                          <font size="1">
                            <u>
                              <%= link_to "reply", "/comments/#{comment.id}" %>
                            </u>
                          </font>
                        </p>
                      </div>
                    </span>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <% end %>
      </tbody>
  </table>
  <br><br>
</td>